Fix SpadeAnalysisPlugin.cpp error, 'fileIndex': undeclared identifier
Removed the assert statement from `SpadeAnalysisPlugin::downsample` which caused a compilation error from the Debug configuration:

    SpadeAnalysisPlugin.cpp(368): error C2065: 'fileIndex': undeclared identifier

Was discussed last week at slack #hdps: https://biovault.slack.com/archives/CKLNDA6SY/p1561392161033300